import 'package:json_annotation/json_annotation.dart';

part 'user_model.g.dart';

@JsonSerializable()
class UserModel {
  final String name;
  final String email;
  final String? token;
  final String? image;
  @JsonKey(name: 'Visa')
  final String? visa;
  final String? address;

  UserModel({
    required this.name,
    required this.email,
    this.token,
    this.image,
    this.visa,
    this.address,
  });

  // factory generated by json_serializable
  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);

  Map<String, dynamic> toJson() => _$UserModelToJson(this);

  @override
  String toString() {
    return '$name ------ $visa';
  }
}
