import 'package:json_annotation/json_annotation.dart';

import '../../../core/utils/exported_file.dart';

part 'auth_model.g.dart';

@JsonSerializable()
class AuthModel {
  final String name;
  final String email;
  final String? token;
  final String? image;

  AuthModel({required this.name, required this.email, this.token, this.image});

  // factory generated by json_serializable
  factory AuthModel.fromJson(Map<String, dynamic> json) =>
      _$AuthModelFromJson(json);

  Map<String, dynamic> toJson() => _$AuthModelToJson(this);
}
