import 'package:json_annotation/json_annotation.dart';

import '../../../core/utils/exported_file.dart';

part 'user_model.g.dart';

@JsonSerializable()
class UserModel {
  final String name;
  final String email;
  final String? token;
  final String? image;
  @JsonKey(name: 'Visa')
  final String? visa;
  final String? address;

  UserModel({
    required this.name,
    required this.email,
    this.token,
    this.image,
    this.visa,
    this.address,
  });

  // factory generated by json_serializable
  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);

  Map<String, dynamic> toJson() => _$UserModelToJson(this);

  Future<FormData> toFormData() async {
    final data = <String, dynamic>{
      'name': name,
      'email': email,
      'address': address,
    };

    if (visa != null && visa!.isNotEmpty) {
      data['Visa'] = visa;
    }

    // ✅ Image is optional — handled safely here
    if (image != null && image!.isNotEmpty) {
      data['image'] = await MultipartFile.fromFile(
        image!,
        filename: 'upload.jpg',
      );
    }

    return FormData.fromMap(data);
  }

  @override
  String toString() {
    return '$name ------ $visa';
  }
}
